### ISSUE TITLE
Cannot find module 'bluebird' sometimes

### ISSUE THREAD

**Issue by ivankahl** [joway/sheetsql#8]
I am trying to use this package (awesome package by the way!) in a Netlify Function. When I develop locally everything works fine (on Windows). However, when I deploy to Netlify (which I assume is Linux) and try and invoke the function I get this error:

```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'bluebird'\nRequire stack:\n- /var/task/src/node_modules/sheetsql/dist/src/storage.js\n- /var/task/src/node_modules/sheetsql/dist/src/db.js\n- /var/task/src/node_modules/sheetsql/dist/src/index.js\n- /var/task/src/functions/utils/getCurrentMeetings.js\n- /var/task/src/functions/getMeetings.js\n- /var/task/getMeetings.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "stack": [
    "Runtime.ImportModuleError: Error: Cannot find module 'bluebird'",
    "Require stack:",
    "- /var/task/src/node_modules/sheetsql/dist/src/storage.js",
    "- /var/task/src/node_modules/sheetsql/dist/src/db.js",
    "- /var/task/src/node_modules/sheetsql/dist/src/index.js",
    "- /var/task/src/functions/utils/getCurrentMeetings.js",
    "- /var/task/src/functions/getMeetings.js",
    "- /var/task/getMeetings.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
    "    at Module.load (internal/modules/cjs/loader.js:986:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

I searched around and it seems like other libraries also have a similar issue and seems to be caused by case-sensitivity on some operating systems. I know Linux is case-sensitive and Windows isn't so I suspect that might be an issue.

I looked at the sheetsql code but am struggling to see how it's not finding the module.  Could you maybe point me in the right direction?

**Comment by joway** [comment]
Hi, @ivankahl , that's a bug and fixed it at https://github.com/joway/sheetsql/commit/b2aabaa45ee3b8d7f1bae48564e95886a7c9b086

Please try the latest version 0.1.7.

Thanks for your issue!

**Comment by ivankahl** [comment]
Awesome that seems to have fixed that error. I'm now getting this issue now I'm not sure if it's related? This seems to be happening when I try and create a new Database object.

```json
{
  "errorType": "StorageOptionsError",
  "errorMessage": "",
  "name": "StorageOptionsError",
  "stack": [
    "StorageOptionsError",
    "    at new class_1 (/var/task/src/node_modules/sheetsql/dist/src/utils/error.js:23:36)",
    "    at new GoogleStorage (/var/task/src/node_modules/sheetsql/dist/src/storage.js:81:19)",
    "    at new Database (/var/task/src/node_modules/sheetsql/dist/src/db.js:42:24)",
    "    at module.exports (/var/task/src/functions/utils/getCurrentMeetings.js:7:14)",
    "    at Runtime.exports.handler (/var/task/src/functions/getMeetings.js:7:32)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

**Comment by joway** [comment]
It seems that you create Database wrong. Could you show me your code?

**Comment by ivankahl** [comment]
You were right the key file did not exist.
